# Generated by Django 4.2.5 on 2023-09-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdnests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Birdnest',
        ),
    ]
